### ISSUE TITLE
Deleting a subscription shouldn't require a customer id

### ISSUE THREAD

**Issue by hanrelan** [princemaple/extripe#12]
While creating a subscription requires a customer id, deleting a subscription doesn't according to the stripe api. The subscription module's delete should allow deleting a subscription without the customer id, ie:
`Extripe.Subscription.delete "customer_id"`

**Comment by princemaple** [comment]
Good point. I'll take a look soon.

**Comment by princemaple** [comment]
Looks like subscription is a special case here. All other resources that require a scope either require it on delete or do not allow deletion. I'll make a simple overwrite to special case it.

**Comment by princemaple** [comment]
fixed in https://github.com/princemaple/extripe/commit/eceeed63f239094aca626d89603adc7b4aeb939f and released v1.2.1

**Comment by princemaple** [comment]
looks like subscriptions#show needs fixing as well. *shrug*

**Comment by princemaple** [comment]
OK turns out Stripe has some weird api versioning strategy. They obviously have changed their subscription API completely without bumping APIv1 to v2.

**Comment by princemaple** [comment]
I've updated it to the latest version in v1.2.2
Now subscriptions are no longer scoped to customers.
However, you can still list subscriptions under a customer by passing options to index, e.g. `Extripe.Subscription.index(customer: CUSTOMER_ID)`
Subscription creation now not only requires `plan: PLAN_ID` but also `customer: CUSTOMER_ID`
All other actions (i.e. `show`, `update`, `delete`) work on a SUBSCRIPTION_ID, e.g. `Extripe.Subscription.update(SUBSCRIPTION_ID)` and `Extripe.Subscription.delete(SUBSCRIPTION_ID)`

**Comment by hanrelan** [comment]
Awesome, thanks for the super quick response. I'll update to this and let
you know if I have any issues
