### ISSUE TITLE
Unable to specify stripe_secret_key when making request

### ISSUE THREAD

**Issue by nicksanders** [princemaple/extripe#9]
There is no way to work with multiple stripe accounts

**Comment by princemaple** [comment]
@nicksanders thanks for reporting. Didn't think of this use case. Could briefly describe when/why one would want to do so?

**Comment by princemaple** [comment]
Also, I have no idea how I missed this.

**Comment by princemaple** [comment]
> Could briefly describe when/why one would want to do so?

So I can abstract that one properly.

**Comment by nicksanders** [comment]
If you have a multi tenant application, different users can have different stripe accounts. You need to be able to pass the stripe_secret_key on the request

**Comment by princemaple** [comment]
Use stripe connect for that?
